# Generated by Django 3.2.4 on 2021-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='auc_image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
