# Generated by Django 4.1 on 2022-09-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
