# Generated by Django 3.2.4 on 2021-07-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_auc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='auc_image',
            field=models.ImageField(blank=True, default='rose.jpg', upload_to=''),
        ),
    ]
